### ISSUE TITLE
ERROR database.py

### ISSUE THREAD

**Issue by strunz983** [scmanjarrez/CVEScannerV2#15]
Hello i get this message after python3 update 
old python3 ver Python 3.11.9
new python3 ver Python 3.12.6

message is 
python3 database.py -d cve.db
Traceback (most recent call last):
  File "/CVEScannerV2/extra/database.py", line 41, in <module>
    from pyrate_limiter import Limiter, RequestRate
ModuleNotFoundError: No module named 'pyrate_limiter'

My OS is Linux kali 6.8.11-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.8.11-1kali2 (2024-05-30) x86_64 GNU/Linux
Thank you :)

**Comment by scmanjarrez** [comment]
Hi, are you by any chance using the default Python installation? Have you set up a virtual environment and installed the required packages? If you'd prefer to avoid dealing with dependency issues, you could also run the script using the docker container, which is already configured and up to date.

**Comment by strunz983** [comment]
Hello I make this 
pip3 install -r requirements.txt --ignore-installed
and now is working on Python 3.12.6 no error no more 
Thank you
