### ISSUE TITLE
Parsing Error

### ISSUE THREAD

**Issue by ablito19** [scmanjarrez/CVEScannerV2#3]
Hello world,

I got this error

Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 20988183: character maps to <undefined>.

Any support

**Comment by scmanjarrez** [comment]
Can you give more information about this error? What were you doing when this happened? Did you used provided database? Did you create your own database?

**Comment by scmanjarrez** [comment]
Could you pull latest commit? I've updated database script. I've tested it with windows 10 + python3.10.2 and seems to work now.

**Comment by ablito19** [comment]
it seem working now. thank you so much

**Comment by scmanjarrez** [comment]
Fixed in cacbb5fac83fc0c13c75e11f984f75052174061a
