### ISSUE TITLE
attempt to index a nil value (local 'cur')

### ISSUE THREAD

**Issue by wizardlevel9** [scmanjarrez/CVEScannerV2#4]
This is the error when running nmap in debug mode:

NSE: [GetaSploit 192.168.0.184:21] Nmap detection worked.
NSE: [GetaSploit 192.168.0.184:21] Nmap detection: cpe => cpe:/a:vsftpd:vsftpd:3.0.3 | version => 3.0.3
NSE: [GetaSploit 192.168.0.184:21] CVEScannerV2 detection worked.
NSE: [GetaSploit 192.168.0.184:21] CVEScannerV2 detection: product => vsftpd | version => 3.0.3 | vupdate => * | range_from => nil | range_to => nil
NSE: GetaSploit against 192.168.0.184:21 threw an error!
/usr/bin/../share/nmap/scripts/CVEScannerV2.nse:511: attempt to index a nil value (local 'cur')
stack traceback:
	/usr/bin/../share/nmap/scripts/CVEScannerV2.nse:511: in upvalue 'vulnerabilities'
	/usr/bin/../share/nmap/scripts/CVEScannerV2.nse:574: in upvalue 'nmap_analysis'
	/usr/bin/../share/nmap/scripts/CVEScannerV2.nse:693: in function </usr/bin/../share/nmap/scripts/CVEScannerV2.nse:668>
	(...tail calls...)

The OS is "22.04.1 LTS (Jammy Jellyfish)"

I've tried multiple Operating Systems and builds and they all have the same issue.

Can you please shed some light on what is causing this error?

Thanks in advance

**Comment by scmanjarrez** [comment]
Mmmm, do you have the database? Seems like it's trying to access the database cursor, but it's nil.

**Comment by wizardlevel9** [comment]
Please close the issue, it is caused by a corrupt database. Thanks for looking into it for me and apologies for wasting your time…by the way, I love what you are doing.

On 9 Feb 2023, at 11:22 pm, Sergio C ***@***.***> wrote:


I've released a new version, can you test latest commit?

**Comment by scmanjarrez** [comment]
I'm glad is working! And thank you :)
